name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.16.0
    - name: Install dependencies
      run: npm install
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Deploy to DigitalOcean Droplet
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME : ${{secrets.SSH_USERNAME}}
        run: |
          sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
          cd /root/onpar/
          git pull origin main
          cd frontend/onpar
          npm install
          VITE_API_URL=/api/auth npm run build
          sudo rm -rf /var/www/mern-frontend/*
          sudo cp -r dist/* /var/www/mern-frontend/
          
          cd /root/onpar/backend
          npm install

          pm2 describe onpar-backend > /dev/null
          if [ $? -eq 0 ]; then
            pm2 restart onpar-backend
          else
            pm2 start src/server.js --name onpar-backend
          fi
          
          pm2 save
          pm2 startup -u $SSH_USERNAME --hp /home/$SSH_USERNAME
          
          sudo systemctl reload nginx
